.rultor.yml

PR for https://github.com/timelesslounge/timelessis/issues/124* add repository for installation 
- python3.6
- add python f-strings (which was added in python 3.6) for checking

#124: install python3.6 to rultor

---

tests/test_models.py
timeless/companies/models.py
timeless/items/models.py

PR for #15
- Added Item Model
- Left puzzle for continuing implementation
- Migration has not been added since it is not possible to generate.

#15 Item Model + Test + Puzzle

---

requirements.txt
tests/integration/it_employees_test.py
tests/test_employees.py
tests/test_sync.py
timeless/employees/models.py
timeless/models.py

For #58:
- Creating constructor for Employee model which sets defaults fields and encrypts password
- Update tests to reflect changes

#58 Employee Constructor + Pwd Encryption (new PR)

---

README.md

#147 
* Added instruction to setup PostgreSQL for Debian / Ubuntu.

#147 Readme update

---

tests/integration/it_employees_test.py
timeless/models.py

#103 
* created test for TimestampsMixin in employees
There is no point in creating unit test because it doesn't make sense for a class that needs database.

#103 created test for TimestampsMixin

---

tests/test_sync.py
timeless/sync/sync.py

For #88: Implemented `Location` sync logic
* Implemented `sync.py` `sync_location` logic to sync the objects received
* Corrected test to compare objects correctly
* Left puzzle for database implementation

For #88: Location sync logic

---

README.md

#147 Small clarification about installing PostgreSQL on local machine

#147 Readme clarification about Postgres setup

---

tests/test_sms.py
timeless/sms.py

PR for https://github.com/timelesslounge/timelessis/issues/125
- add decorator class to handle fails SMS API and retrying send sms
- add tests

#125: add decorator for retrying send sms

---

Dockerfile
README.md
config.py
docker-compose.yaml
entrypoint.sh
manage.py

#35 
Introduced Docker and Docker Compose setup. README file has been updated.

#35 Init Docker

---

.pdd
tests/test_table_shapes.py
timeless/__init__.py
timeless/restaurants/models.py
timeless/restaurants/table_shapes/views.py
timeless/templates/restaurants/table_shapes/create_edit.html
timeless/templates/restaurants/table_shapes/list.html

#72 
* added initial table shapes views
* todo for continuation
* added `.idea` to exclusions in pdd, so it will work locally without any problems

#72 initial table shapes views

---

tests/conftest.py
tests/test_floors.py
timeless/auth/views.py
timeless/restaurants/floors/views.py

For #60:
- created method to check session before each request and put user into request scope
- implemented login_required decorator - applied it for floors view

#60 Checking session and login decorator

---

tests/test_tables.py
timeless/__init__.py
timeless/restaurants/models.py
timeless/restaurants/tables/views.py
timeless/templates/restaurants/tables/create_edit.html
timeless/templates/restaurants/tables/list.html

#112 
* created initial views for tables
* todo for continuing implementation

#111 initial tables views

---

timeless/__init__.py
timeless/reservations/controllers.py
timeless/reservations/views.py

PR for #63
* Moved Reservation Settings methods into a class
* Created SettingsController and left puzzles
Already reviewed by @paulodamaso in #128 (initial PR was closed because the repo became public and had to be reforked)

SettingsController for Reservations and puzzle

---

tests/poster_mock.py
tests/test_poster.py
timeless/poster/api.py
timeless/restaurants/models.py
timeless/sync/sync.py

For #24,
updated model and expanded Poster api. Left a puzzle for further development.

#24 Poster Tables sync

---

README.md
scripts/backup/pg_backup.config
scripts/backup/pg_restore.sh

#114 
* added restore script and removed todo
* renamed the USERNAME variable to USR (USERNAME is used by shells and always contains the current user, so it wasn't loading the one set in config)

#114 added restore scripts

---

tests/test_roles.py
timeless/__init__.py
timeless/roles/views.py
timeless/templates/roles/create_edit.html
timeless/templates/roles/list.html

#96 
* implemented initial views for roles management
* todo to continue implementation

#96 initial role views

---

timeless/roles/models.py

#96 removed todo

---

tests/integration/it_locations_test.py
timeless/restaurants/locations/views.py

For #133: Locations integration test.
- Added Location integration test
- Left puzzle for continuing location implementation

For #133: Locations integration test.

---

timeless/restaurants/models.py

For #172: Todo removal

---

README.md
docker-compose.yaml
timeless/__init__.py

For #211: Redis installation
- Added `Redis` installation instructions to `README.md`
- Added `Redis` installations execution to `docker-compose.yaml`

For #211: Redis installation

---

config.py
deploy.sh
main.py

For #126:
- Implementing reading the credentials.json and using private key and username to connect to staging server, transfer files and execute commands
- leaving puzzle to finish adding cron scripts and creating curl requests to test that application is running ok

#126 Implementing SSH private key connection to staging

---

timeless/templates/base.html
timeless/templates/restaurants/floors/list.html
timeless/templates/restaurants/locations/list.html
timeless/templates/restaurants/reservations/create_edit.html
timeless/templates/restaurants/table_shapes/list.html

#216 
Use cache directive only in base template

#216 Fix template caching

---

tests/test_owner_privilages.py
timeless/access_control/methods.py
timeless/access_control/owner_privileges.py

For #180 , continued with owner privileges implementation. Left one puzzle.

#180 owner privilages (Employee access)

---

tests/integration/it_poster_test.py

#113 
Readding a puzzle that was wrongly removed

Issue #113 - Adding a puzzle that was wrongly removed

---

tests/integration/it_poster_test.py

Issue #113 - Modified id

---

deploy.sh
scripts/install/deploy/install_db.sh
scripts/install/deploy/install_dependencies.sh
scripts/install/deploy/install_python.sh
scripts/install/deploy/install_redis.sh

For #240:  Implemented Python and Postgres availability check
* Added puzzle to compete the effort by adding redis availability check and define/cover rest of dependencies
* Added `venv` creation instruciton

For #240: Implemented Python and Postgres availability check

---

.codeclimate.yml
.travis.yml

For #86:
- Adding `.travis.yml` to build and test with coverage
- Adding `.codeclimate.yml` to run code checks and analysis

#86 Travis and Code Climate configuration

---

tests/integration/it_poster_test.py
tests/test_auth.py
tests/test_sync.py
timeless/poster/api.py
timeless/poster/exceptions.py

PR for https://github.com/timelesslounge/timelessis/issues/197
- added oauth2 to poster api logic, getting auth_token
- fix tests

197: add oauth2 to poster logic

---

tests/test_table_shapes.py
timeless/restaurants/table_shapes/views.py
timeless/templates/views.py

For #203 , added order by in Table shape view

#203 table shapes order by

---

config.py
docker-compose.yaml
entrypoint.sh
requirements.txt
timeless/__init__.py
timeless/customers/models.py
timeless/sync/celery.py
timeless/sync/synced_customer.py
timeless/sync/synced_location.py

For #225: Added celery to manage synchronization executions
- Added `celery` execution to `entrypoint.sh`
- Added `celery` to `requirements.txt`
- Added `celery`  code to make jobs
- Added `synced_customer.py` stub
- Added puzzle for continuing implementation
- Added puzzle to make Location sync routine with celery

For #225: Added celery to manage synchronization executions

---

timeless/restaurants/locations/views.py
timeless/views.py

PR for https://github.com/timelesslounge/timelessis/issues/134
Set up skeleton for generic views.

134: Setup generic template views

---

tests/integration/it_poster_test.py
tests/test_poster.py

For #155:
- Reverting it_poster_test.py and test_poster.py

#155 Reverting it_poster_test and test_poster modules

---

.coverage
tests/integration/it_auth_test.py
tests/integration/it_employees_test.py
tests/integration/it_owner_privilages_test.py
tests/integration/it_sync_test.py
tests/integration/it_table_shapes_test.py
tests/test_models.py
timeless/companies/__init__.py
timeless/companies/models.py
timeless/customers/models.py
timeless/employees/models.py
timeless/items/models.py
timeless/reservations/models.py
timeless/restaurants/models.py
timeless/restaurants/table_shapes/views.py
timeless/schemetypes/models.py

For PR #149:
The validate_required decorator has been implemented for all models in which require verification of mandatory parameters.

#149 Implemented validate_required decorator for all models

---

tests/integration/it_administrator_privilages_test.py
timeless/access_control/__init__.py
timeless/access_control/administrator_privileges.py
timeless/access_control/authorization.py

#174 
* added administrator role privileges
* added test to verify them

#174 added Administrator role

---

tests/integration/it_director_privilages_test.py
timeless/access_control/__init__.py
timeless/access_control/authorization.py
timeless/access_control/director_privileges.py

#175 
* added director role privileges
* added tests to cover that
* added todo to add roles to employees and continue implementation

#175 add director role privileges

---

tests/integration/it_table_shapes_test.py
timeless/restaurants/__init__.py
timeless/restaurants/table_shapes/views.py

#206 
* added editing of a Table Shape
* added test to validate it
* made delete test more like an integration test (less db session)
* added import of dependent models in restaurants __init__.py (so it will reliably work in both CLI and IDE)

#206 added edit for table shape

---

tests/integration/it_director_privilages_test.py
tests/integration/it_manager_privilages_test.py
tests/integration/it_owner_privilages_test.py
timeless/access_control/authorization.py
timeless/access_control/manager_privileges.py

#176
* added manager role priviledges
* added tests to cover that
* todo for checking also roles

#176 add manager role priviledges

---

scripts/install/deploy/install_db.sh
scripts/install/deploy/install_redis.sh

#248: Implemented Redis availability check, installation and launch
* Aligned `install_db.sh` messaging
@emilianodellacasa Not quite if if there are any other dependencies to check?

#248: Implemented redis availability check, installation and launch

---

timeless/access_control/__init__.py

#176 remved puzzle

---

timeless/auth/auth.py

For #269: Removing todo.

---

config.py
tests/conftest.py
tests/integration/it_floors_test.py
tests/integration/it_reservation_settings_test.py
timeless/__init__.py
timeless/reservations/views.py
timeless/restaurants/floors/views.py
timeless/templates/restaurants/floors/list.html
timeless/views.py

For #173:
- Refactoring GenericView, implementing ListView and DetailView
- Left puzzles for further development

#173 Implementing GenericView, ListView and DetailView

---

tests/integration/it_table_shapes_test.py
timeless/restaurants/table_shapes/views.py
timeless/templates/views.py

Fixes #260.  Implemented filter_by table_shapes.list route argument.
* Implemented route argument, 
* Route argument parsing to query
* Test to check argument parsing
* Test to check HTML returned contains table shapes of interest
* Several puzzles added to encapsulate Page Object parsing and to enable assertions one [caching](https://github.com/timelesslounge/timelessis/issues/273) issue is fixed

#260: Implemented filter_by table_shapes.list route argument.

---

config.py
tests/integration/it_floors_test.py
timeless/__init__.py
timeless/cache/__init__.py
timeless/templates/base.html
timeless/templates/items/list.html
timeless/templates/restaurants/floors/list.html
timeless/templates/restaurants/locations/list.html
timeless/templates/restaurants/table_shapes/list.html
timeless/templates/restaurants/tables/list.html
timeless/templates/roles/list.html

Solved problems in #273
1- cache is accessible from any module by importing it.
2- Redis hostname is being set from config.
3- removed cache from the base template.

Cache problems #273

---

.rultor.yml
deploy.sh
release.sh

#239: Added tag and environment arguments to `deploy.sh`. Moved deploy script invocation in `.rultor.yml` from `deploy` to `release`, environment is hard-coded for the meantime (see https://github.com/timelesslounge/timelessis/issues/239#issuecomment-464585020).

#239 Added tag and environment args to deploy.sh

---

docker-compose.yaml
tests/integration/it_companies_test.py
tests/test_authorization.py
timeless/access_control/authorization.py
timeless/access_control/methods.py
timeless/access_control/views.py

#183 
* Checking permissions in SecuredView
* docker-compose fixed

#183 Checking permissions in SecuredView

---

timeless/access_control/views.py

#183 Removed forgotten todo
It was done in https://github.com/timelesslounge/timelessis/pull/319

#183 Remove todo

---

tests/conftest.py
tests/integration/it_floors_test.py

PR for #305 
Removed the fixture and tests are fine

#305 removed the fixture

---

tests/integration/it_auth_test.py
timeless/auth/views.py
timeless/templates/auth/forgot_password.html

For #200: Forgot password page and tests
- Create forgot password page
- Create test for forgot password page

For #200: Forgot password page and tests

---

tests/integration/it_manager_privilages_test.py
timeless/employees/models.py

For #298: 
- Added `Role` to `Employee`
- Added test for checking if `Manager` can't access `Director`
- Left todo for continue the implementation

For #298: Added test checking that manager does not have access to

---

config.py
tests/integration/sync/it_sync_tables_test.py
timeless/poster/api.py
timeless/poster/tasks.py
timeless/restaurants/models.py
timeless/schemetypes/models.py
timeless/sync/sync.py

https://github.com/timelesslounge/timelessis/issues/187 : 
- Implemented periodic task for fetching tables from Poster
- Left puzzles for continue implementation and refactor

#187: Implement periodic task for fetching tables

---

tests/conftest.py
tests/integration/it_employees_test.py
timeless/__init__.py
timeless/employees/views.py
timeless/templates/employees/list.html

For #57:
- Implementing Employees list view
- Leaving comments and puzzle for further development

#57 Implementing Employees list

---

README.md
scripts/backup/pg_backup.sh

#296 
* recover the last uploaded DB Backup gdrive ID and display it for the user
* added puzzle to automate this step

#296 recover the last uploaded DB Backup gdrive ID and display it for the user

---

tests/integration/it_reservation_settings_test.py

#291 
* added tests for reservation settings
* todo to tune and enable the tests when the functionality will be ready

#291 added tests for reservation settings

---

config.py
docker-compose.yaml
tests/conftest.py
tests/factories.py
tests/integration/it_administrator_privilages_test.py
tests/integration/it_other_privilages_test.py
timeless/access_control/__init__.py
timeless/access_control/authorization.py
timeless/access_control/other_privileges.py

#178 
* checking permissions for Master / Intern / Other roles
* add tests
* fix docker setup

#178  Master / Intern / Other role permissions

---

timeless/employees/models.py
timeless/employees/views.py

For #57:
- Removing puzzle in order to close the job
- Adding puzzle to add filtering and sorting to list view

#57 Removing and fixing puzzles

---

tests/integration/poster/poster_server_mock.py
tests/integration/poster/poster_server_mock_test.py
tests/integration/sync/it_sync_location_test.py
tests/poster_mock.py

For #232: Poster mock server refactor
- Added `PosterServerMock` generic mock server, to be subclassed
- Added tests for generic `PosterServerMock` behaviors

For #232: Poster mock server refactor

---

timeless/access_control/manager_privileges.py

For #298: Removing puzzle

---

tests/test_items.py
timeless/items/models.py

For #318:
- Implemented item_history method
- Implemented item assign method

For #318: Added Item history 

---

tests/factories.py
tests/integration/it_tables_test.py
tests/test_models.py
timeless/restaurants/models.py
timeless/restaurants/tables/forms.py
timeless/restaurants/tables/views.py
timeless/views.py

#307 
* CreateView implemented
* tests fixed

#307 CreateView implementation

---

pylintrc

#168 
* removed exclusion of whole module
* added exclusion of specific classes that have members dynamically generated

#168 less pylint excludes

---

release.sh

Removing the puzzle for issue #238

#238 Removing puzzle for closed issue

---

scripts/install/deploy/install_db.sh
scripts/install/deploy/timeless_pg.service
scripts/install/install_db.sh
scripts/service/timeless_pg.service

For #299 :
Implementation of the service that can be used to check if `Postgres` is available after restarting the server.
**Copy the file to:**
/lib/systemd/system
**After:**
sudo systemctl start timeless_pg.service

#299 Implementation of the service - Postgres

---

tests/integration/sync/it_sync_tables_test.py
timeless/sync/synced_table.py

For #342: Table sync with poster
- Added `SyncedTable` skeleton
- Added `SyncedTable` tests

For #342: Table sync with poster

---

tests/conftest.py
tests/integration/it_scheme_types_test.py
timeless/schemetypes/models.py
timeless/schemetypes/views.py
timeless/templates/schemetypes/schemeconditions/list.html

For #97:
- Implementing Scheme Conditions list view by `scheme_type_id`
- Leaving puzzle to implement other views (create, update, delete)
- Fixing tests to run faster (I guess by mistake `conftest.py` was reverted to older code)

#97 Implementing Scheme Conditions List view

---

tests/integration/it_auth_test.py
timeless/auth/auth.py
timeless/auth/views.py
timeless/templates/auth/forgot_password_post.html

For #370: Forgot password post screen and logic
- Created test that checks if the page showed after forgot password post is right
- Created forgot password post screen
- Corrected the test in forgt password

For #370: Forgot password post screen and logic

---

tests/conftest.py
tests/factories.py
tests/integration/it_manager_privilages_test.py
tests/integration/it_roles_test.py
timeless/access_control/manager_privileges.py
timeless/employees/models.py
timeless/roles/models.py

#341 
* Manager can access to Master / Intern accounts
* tests fixed

#341 Manager can edit master / intern roles

---

timeless/restaurants/models.py

For #342: I've forgot to remove the todo, and I've noticed that I didn't remove the procedural methods that were supressed by `SyncedTable` implementation.
- Removed todo 
- removed methods that does not make sense anymore

For #342: Removed todo and methods that does not make sense anymore

---

timeless/customers/models.py
timeless/poster/tasks.py
timeless/sync/synced_customer.py

For #262 added sync between `Customer` and `Poster`. Left two puzzles for further development

#262 Customer Sync with Poster

---

requirements.txt
tests/integration/it_table_shapes_test.py
timeless/__init__.py
timeless/restaurants/table_shapes/forms.py
timeless/restaurants/table_shapes/views.py
timeless/uploads/__init__.py

#205: Implemented base flow for uploaded image save
* Added number of puzzles to complete the effort

#205: Implemented base flow for uploaded image save

---

tests/integration/it_companies_test.py
timeless/access_control/authorization.py
timeless/access_control/methods.py
timeless/access_control/owner_privileges.py
timeless/companies/views.py

#330 
* Fix passing args in base class responsible for permissions
* fix company permissions for owner role

#330 Fix company permissions & test

---

tests/integration/it_reservations_test.py
timeless/reservations/views.py
timeless/restaurants/models.py
timeless/templates/reservations/list.html

For #380 :
- Fixed some problems found in the form test.
- Including puzzle with problem encountered in status validation (enum).

 #380 Corrections in form validation

---

tests/integration/it_table_shapes_test.py
timeless/restaurants/table_shapes/views.py
timeless/views.py

#312  
* DeleteView implemented
* delete view in table shape endpoint refactored

#312 DeleteView implementation and using it

---

timeless/auth/auth.py

PR for #389 
Removed the puzzle as it's no longer needed

#389 Removed the puzzle

---

tests/view/items/test_items.py
timeless/items/forms.py
timeless/items/views.py
timeless/views.py

For #311: Added `ItemCreateView`
- Added `ItemCreateView` implementation

For #311: Added ItemCreateView

---

tests/conftest.py
tests/factories.py
tests/integration/it_reservations_test.py
tests/test_reservation.py
timeless/__init__.py
timeless/customers/models.py
timeless/reservations/views.py
timeless/restaurants/models.py
timeless/templates/reservations/create_edit.html

PR for https://github.com/timelesslounge/timelessis/issues/236:
- created all it tests for reservations
- refactored old tests
- removed old useless tests

 #236: implement it tests for reservation

---

tests/integration/sync/it_sync_location_test.py
timeless/sync/synced_location.py

For #212: Location sync implementation
- Implemented `Location` sync with `Poster`
- Refactored `SyncedLocation`
- Added puzzle to refactor `it_sync_location_test.py` to use factories

For #212: Location sync implementation

---

tests/view/crudapi/test_crud_api.py
timeless/views.py

+ Uncommented tests, updated puzzle, added new puzzle for new CrudAPIView tests

#289 added CrudAPIView get implementation

---

README.md
scripts/backup/pg_backup.config
scripts/backup/pg_backup.sh
scripts/backup/pg_restore.sh

For #352 : Automate the setting up of FILE_ID into pg_backup.config, we already have the FILE_ID in the script, so what's left is to change it in file

#352 Automate the setting up of FILE_ID into pg_backup.config

---

tests/view/test_reservations.py

#236: 
- Remove puzzle, because I forgot do it in https://github.com/timelesslounge/timelessis/pull/435 . Work is done

#236: remove puzzle

---

tests/conftest.py
tests/factories.py
tests/integration/it_scheme_types_test.py
timeless/schemetypes/forms.py
timeless/schemetypes/models.py
timeless/schemetypes/views.py
timeless/templates/schemetypes/schemeconditions/create_edit.html
timeless/views.py

#386 
* create view for schema conditions
* tests

#386 CreateView for schema conditions

---

timeless/__init__.py
timeless/reservations/views.py

For #306: Implementing reservation Settings views according to generic views.

For #306: Implementing reservation Settings views

---

timeless/auth/views.py

#60 Removing puzzle that wasn't removed

---

tests/integration/it_auth_test.py
timeless/auth/auth.py
timeless/employees/models.py
timeless/templates/auth/login.html

#283: Implemented password verification for login call
Enhanced test to check success login

#283: Implemented password verification for login call

---

tests/integration/it_table_shapes_test.py
timeless/__init__.py
timeless/restaurants/table_shapes/forms.py
timeless/restaurants/table_shapes/views.py
timeless/views.py

#285 
* `UpdateView` implemented
* test for editing table shapes

#285 EditView for table shapes

---

timeless/schemetypes/views.py

#386 puzzle removed.
task was resolved in https://github.com/timelesslounge/timelessis/pull/446 PR

#386 remove forgotten puzzle

---

timeless/restaurants/tables/views.py

PR for #214 
* refactored all endpoint procedures from Tables ``views.py`` to use the existing generic view classes
* removed ticket puzzle
* removed old puzzle (the one originating from ticket ``112``) because it was also obsolete (see discussion [here](https://github.com/timelesslounge/timelessis/issues/170))
**Edit**: I'm not exactly sure whether the HTML pages (navigation from Location views, for instance) are implemented or I should leave a puzzle.

#214 class views for Table, removed puzzles

---

tests/view/items/test_items.py
timeless/auth/auth.py
timeless/items/views.py
timeless/views.py

PR for https://github.com/timelesslounge/timelessis/issues/308:
- added permissions for GenericViews
- added `auth.login_required` to `ItemCreateView` as test
- added tests for that

#308: add permissions to GenericViews

---

tests/factories.py
tests/integration/it_director_privilages_test.py
tests/integration/it_manager_privilages_test.py
timeless/roles/models.py

PR for #397 
Added enumeration for role types.
Used the enumeration instead of names for tests.
Left a puzzle to remove the name.

#397 added the role type enumeration

---

tests/integration/it_auth_test.py
tests/integration/it_roles_test.py
tests/test_auth.py
timeless/auth/auth.py
timeless/auth/views.py

#387 
* Mask email with asterisks + tests

#387 Mask email with asterisks

---

scripts/install/deploy/install_db.sh

For #374: Implementing timeless user creation:
- creates database if it does not exists
- creates user if it does not exists
- create Timeless company and user

 For #374: Implementing timeless user creation

---

tests/conftest.py
tests/factories.py
tests/integration/it_locations_test.py
timeless/restaurants/locations/views.py
timeless/templates/restaurants/locations/list.html

PR for https://github.com/timelesslounge/timelessis/issues/363:
- removed old func based views
- added class based views
- fixed and refactored tests

#363: removing func based views

---

tests/integration/it_roles_test.py
timeless/roles/views.py

#338 
* EditView for roles + tests

#338 Edit view for roles

---

timeless/auth/views.py

For #385: Todo removal

---

tests/integration/it_floors_test.py
timeless/restaurants/floors/views.py
timeless/templates/restaurants/floors/list.html

For issue #424:
- refactored test to support generic views;
- added link to floor list pages to delete floor;
- left puzzle to ask for confirmation before deleting;

Issue #424 - Implemented delete view for floors

---

tests/integration/it_employees_test.py
timeless/employees/views.py

#411 Implemented a test submitting updated comment data.
Muted a test adding a puzzle to fix it, since it fails with `Already Exists` message for the `username` and `pincode`.

#411: Implemented a test submitting updated employee data

---

tests/integration/it_owner_privileges_test.py
timeless/access_control/authorization.py
timeless/access_control/owner_privileges.py

#393 
* owner permissions for employee resource + tests

#393 Owner permissions for employee resource

---

tests/factories.py
tests/integration/it_reservations_test.py
tests/view/test_reservations.py
timeless/reservations/views.py
timeless/templates/reservations/list.html

PR for https://github.com/timelesslounge/timelessis/issues/484:
- fixed ReservationViews
- fixed all tests
- removed useless tests

#484: fix reservation views and tests

---

tests/integration/it_auth_test.py

PR for #465
- Added a test for forgot the password logic.

#465 added a test for forgot password.

---

tests/integration/it_authorization_test.py
tests/integration/it_owner_privileges_test.py
timeless/access_control/authorization.py
timeless/access_control/owner_privileges.py
timeless/roles/models.py

PR for https://github.com/timelesslounge/timelessis/issues/358:
- fixed tests
- fixed some logic in privileges module

#358: fix auth tests

---

tests/view/items/test_items.py

For #417:  `ItemListView`  test with authentication.
- Corrected the `ItemListView` session problem using other logic to create fake objects
- Left puzzle for correcting `ItemListView` behavior

For #417: ItemListView test with authentication.

---

tests/integration/it_employees_test.py
timeless/employees/views.py

For #412: Delete "template_name" from Delete 
- Removed asked variable from `Delete`
- Corrected `Delete` test with authentication.
- Left puzzle to fix `Delete` (it is not working)

For #412: Delete "template_name" from Delete

---

tests/view/crudapi/test_crud_api.py
timeless/views.py

#449 
Adding CRUD methods to FakeModel and CrudAPIView, adding appropriate tests

Adding CRUD methods to FakeModel and CrudAPIView

---

tests/test_models.py
timeless/customers/models.py

#410 
When merging with Poster, we create a new Customer instance with some fields coming from poster. When creating a new instance from Poster, all the fields come from poster.

Implemented Poster merge and create for Customer

---

tests/conftest.py
tests/integration/it_floors_test.py
timeless/restaurants/floors/forms.py
timeless/restaurants/floors/views.py
timeless/templates/restaurants/floors/create_edit.html

For issue #422
- fixed auth.login, now the function can be used to login in tests;
- continue with create view development;
- left puzzle to show inserted information;

Issue 422 - Continue on create floor view and left puzzle

---

tests/test_auth.py
timeless/auth/views.py

For issue #485 
- i correctly set the session user and flag to be recognized as logged_in;
- fixed view that was calling `commit()` on wrong object;

Issue #485 - Fixed user activation test

---

timeless/access_control/owner_privileges.py

#392 removed the puzzle

---

tests/view/table_shapes/test_table_shapes.py
timeless/restaurants/table_shapes/views.py
timeless/templates/restaurants/table_shapes/list.html

#316
Added a simple html form with the description field

Adding HTML filter form for TableShape view

---

tests/view/test_generic_views.py
timeless/employees/views.py
timeless/views.py

PR for https://github.com/timelesslounge/timelessis/issues/357:
- created `sort_query` method in ListView
- added test for that

#357: created order method for ListView
